---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume
  namespace: 2-1
  labels:
    app: volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume
  template:
    metadata:
      labels:
        app: volume
    spec:
      volumes:
        - name: vol
          emptyDir: {}
      containers:
        - name: multitool
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http-port
          volumeMounts:
            - name: vol
              mountPath: /input
        - name: busybox
          image: busybox:latest
          command: ['sh', '-c', 'while true; do echo $(date +%d-%m-%Y\ %H:%M:%S) - test message >> /output/test.log; sleep 5; done']
          volumeMounts:
            - name: vol
              mountPath: /output

